<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ include file="header.jsp"%>	

	<div class="container text-content" style=" height:auto;">
		<div class="row">
			<div class="col-md-10 col-md-offset-1" style="font-size: 15px;">
				<h3 class="headerColor">What is Aadhaar Data Vault?</h3>
				<br>
				<p>Data security is of paramount importance, especially for the information that contains personal identity numbers. The Aadhaar number is one such identity for which its secure management while availing various Government services has always remained a concern. Aadhaar data vault (ADV) as a middleware service and solution developed by C-DAC ensures secure storage of encrypted Aadhaar numbers as per UIDAI guidelines. Hardware Security Module (HSM), i.e., a cryptographic device to maintain the digital keys, is used to encrypt/decrypt the Aadhaar numbers. ADV can be seamlessly integrated with the department applications, either by taking it as a product or using it as a National service offered by C-DAC.  C-DAC, Mumbai has developed an Aadhaar Data vault with the support of the Ministry of Electronics and Information Technology (Meity), Govt. of India and provides encrypted storage for Aadhaar numbers.</p>
				
				<p>All the Government departments and/or entities offering citizen services and using Aadhaar numbers in their application workflows for any purpose are supposed to use Aadhaar Data Vault for secure management of Aadhaar numbers. These citizen services can be the disbursement of beneficiary schemes, employee details, scholarship details, health records, etc.</p>
				<p>As per UIDAI, the Aadhaar number stored in the Aadhaar data vault must be mapped with a Reference Key generated by the data vault. 
				</p>
				
				<h4 class="headerColor">Need</h4>
				<br>
				<p>
					To overcome the misuse of Aadhaar numbers and their security by various organizations, UIDAI under the Aadhaar Act and Regulations, 2016, has made it compulsory for the storage of all the Aadhaar numbers in a different repository known as ‘Aadhaar Data Vault’.
				</p>
				<p>
					Organizations that are already having Aadhaar Numbers seeded in their database need to ensure the secure management of Aadhaar Numbers and related data through Aadhaar Data Vault. 
				</p>
				
				<h4 class="headerColor">Benefits</h4>
				<br>
				<p>
					Aadhaar Data Vault (ADV) developed by C-DAC as per UIDAI guidelines, is a REST API-based service for storing encrypted Aadhaar numbers against the reference numbers. ADV is a dedicated separate storage that stores all the Aadhaar numbers encrypted through HSM. A unique reference number generated by the data vault for the Aadhaar Number is stored in the application database.Some of the benefits offered by ADV are listed below:
				</p>
				
				<ul style="padding-left:30px;">
  					<li>Flexibility to choose unique or multiple reference key generation to refer to one Aadhaar Number </li>
  					<li>Secure and Seamless integration with the existing applications through REST API based Aadhaar data vault service </li>
  					<li>Enabled by FIPS 140-2 Certified device to manage Keys used for encryption and decryption</li>
  					<li>Transaction statistics through a Dashboard</li>
  					<li>Audit and Access logs</li>
  					<li>Store your Aadhaar details for batch or individual transactions</li>
  					<li>Operational level control of restricting the API usage</li>
				</ul>
				
				<br/><br/><br/>
			</div>
		</div>
		<br/><br/><br/><br/>
	</div><br/><br/><br/><br/><br/><br/><br/><br/>
	

 <%@ include file="footer1.jsp"%>
	